name: Build

on:
 push:

jobs:
 build:
  name: Build repository
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    node: ['lts/*']
  steps:
   - name: 📥 Checkout code
     uses: actions/checkout@v5
   - name: 📦 Setup PNPM
     uses: pnpm/action-setup@v4
     with:
      standalone: true
   - name: 📦 Setup Node.js ${{ matrix.node }}
     uses: actions/setup-node@v5
     with:
      node-version: ${{ matrix.node }}
      cache: 'pnpm'
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Build
     run: pnpm run build
   - name: 📦 Box up the builds
     uses: actions/upload-artifact@v4
     with:
      name: build
      path: |
       ./packages/*/dist
